.\" Process this file with
.\" groff -man -Tascii exportd.8
.\"
.TH EXPORT.CONF 5 "DECEMBER 2010" Rozo "User Manuals"
.SH NAME
export.conf \- rozo export daemon configuration file
.SH DESCRIPTION
.B export.conf
is manage throw 
.B libconfig
<http://www.hyperrealm.com/libconfig/> and thus complies to the
.B libconfig
grammar.

.SS layout
Transform layout used by rozo. Data will be transform in 
.B forward
chunks, only 
.B inverse 
of them will be need to reconstruct, and they will be distributed over 
.B safe
storages.
  
Valid layouts are :
   - 0 : inverse = 2, forward = 3, safe = 4
   - 1 : inverse = 4, forward = 6, safe = 8
   - 2 : inverse = 8, forward = 12, safe = 16

.SS volume
A volume in Rozo is made by a list of storages managed by a
.B storaged
deamon on dedicate hosts. A storage in this file is an sid (uint16_t)
and an ip or dns name to reach the 
.B storaged
deamon.
.B storaged
can manage several storages.
storages are grouped together in
.B clusters
each cluster should be contain at least 
.B safe
storages of the same capacity. Use a new cluster when scaling with storage of different capacity.

.B warning
modifying or removing sid of storage servers can (will) lead to DATA LOSS !
Adding storages is of course mandatory.

volume =
(
    {
        # First cluster.
        cid = 1;
        sids =
        (
            {sid = 01; host = "host1";},
            {sid = 02; host = "host2";},
            {sid = 03; host = "host3";},
            {sid = 04; host = "host4";},
            {sid = 05; host = "host5";},
            {sid = 06; host = "host6";},
            {sid = 07; host = "host7";},
            {sid = 08; host = "host8";}
            # ...
        );
    },
    {
        # Second cluster.
        cid = 2;
        sids =
        (
            {sid = 09; host = "host9";},
            {sid = 10; host = "host10";},
            {sid = 11; host = "host11";},
            {sid = 12; host = "host12";},
            {sid = 13; host = "host13";},
            {sid = 14; host = "host14";},
            {sid = 15; host = "host15";},
            {sid = 16; host = "host16";}
            # ...
        );
    }
);

.SS exports
exports are directory exported by 
.B exportd
daemon as virtual filesystems for clients. A volume can be used by several exports.

exports = (
    {eid = 1; root = "/path/to/foo";},
    {eid = 2; root = "/path/to/bar";}
);

.SH FILES
.I /etc/rozo/export.conf (/usr/local/etc/rozo/export.conf)
.RS
The system wide configuration file.
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.\".SH BUGS
.SH AUTHOR
Fizians <http://www.fizians.com>
.SH "SEE ALSO"
.BR rozo (7),
.BR exportd (8)

