.\" Process this file with
.\" groff -man -Tascii exportd.8
.\"
.TH STORAGE.CONF 5 "DECEMBER 2010" Rozo "User Manuals"
.SH NAME
storage.conf \- rozo storage daemon configuration file
.SH DESCRIPTION
.B storage.conf
is manage throw 
.B libconfig
<http://www.hyperrealm.com/libconfig/> and thus complies to the
.B libconfig
grammar.
.SS storages
A storage in Rozo is directory used by a
.B storaged
deamon to store erase coded data.

.B storaged
deamon.
.B storaged
can manage several storages.

.SS layout
Transform layout used by rozo. Data will be transform in 
.B forward
chunks, only 
.B inverse 
of them will be need to reconstruct, and they will be distributed over 
.B safe
storages.
  
Valid layouts are :
   - 0 : inverse = 2, forward = 3, safe = 4
   - 1 : inverse = 4, forward = 6, safe = 8
   - 2 : inverse = 8, forward = 12, safe = 16

.SS storages
 A storage in this file is an sid (uint16_t)
and an root directory. 

.B warning
sids should be the same as those used in 
.B export.conf

storages = (
    {sid = 01; root = "/path/to/foo";},
    {sid = 02; root = "/path/to/bar";}
    #...
);

.SH FILES
.I /etc/rozo/storage.conf (/usr/local/etc/rozo/storage.conf)
.RS
The system wide configuration file.
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.\".SH BUGS
.SH AUTHOR
Fizians <http://www.fizians.com>
.SH "SEE ALSO"
.BR rozo (7),
.BR storaged (8)

