/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "export_proto.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include "rozo.h"

void
export_program_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		export_path_t exportproc_lookup_1_arg;
		export_uuid_t exportproc_statfs_1_arg;
		export_path_args_t exportproc_stat_1_arg;
		export_path_args_t exportproc_readlink_1_arg;
		export_mknod_args_t exportproc_mknod_1_arg;
		export_mkdir_args_t exportproc_mkdir_1_arg;
		export_path_args_t exportproc_unlink_1_arg;
		export_path_args_t exportproc_rmdir_1_arg;
		export_symlink_args_t exportproc_symlink_1_arg;
		export_rename_args_t exportproc_rename_1_arg;
		export_chmod_args_t exportproc_chmod_1_arg;
		export_trunc_args_t exportproc_trunc_1_arg;
		export_path_args_t exportproc_list_1_arg;
		export_path_args_t exportproc_attr_1_arg;
		export_io_args_t exportproc_read_1_arg;
		export_read_block_args_t exportproc_read_block_1_arg;
		export_io_args_t exportproc_write_1_arg;
		export_write_block_args_t exportproc_write_block_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case EXPORTPROC_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) exportproc_null_1_svc;
		break;

	case EXPORTPROC_LOOKUP:
		_xdr_argument = (xdrproc_t) xdr_export_path_t;
		_xdr_result = (xdrproc_t) xdr_export_lookup_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_lookup_1_svc;
		break;

	case EXPORTPROC_STATFS:
		_xdr_argument = (xdrproc_t) xdr_export_uuid_t;
		_xdr_result = (xdrproc_t) xdr_export_statfs_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_statfs_1_svc;
		break;

	case EXPORTPROC_STAT:
		_xdr_argument = (xdrproc_t) xdr_export_path_args_t;
		_xdr_result = (xdrproc_t) xdr_export_stat_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_stat_1_svc;
		break;

	case EXPORTPROC_READLINK:
		_xdr_argument = (xdrproc_t) xdr_export_path_args_t;
		_xdr_result = (xdrproc_t) xdr_export_readlink_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_readlink_1_svc;
		break;

	case EXPORTPROC_MKNOD:
		_xdr_argument = (xdrproc_t) xdr_export_mknod_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_mknod_1_svc;
		break;

	case EXPORTPROC_MKDIR:
		_xdr_argument = (xdrproc_t) xdr_export_mkdir_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_mkdir_1_svc;
		break;

	case EXPORTPROC_UNLINK:
		_xdr_argument = (xdrproc_t) xdr_export_path_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_unlink_1_svc;
		break;

	case EXPORTPROC_RMDIR:
		_xdr_argument = (xdrproc_t) xdr_export_path_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_rmdir_1_svc;
		break;

	case EXPORTPROC_SYMLINK:
		_xdr_argument = (xdrproc_t) xdr_export_symlink_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_symlink_1_svc;
		break;

	case EXPORTPROC_RENAME:
		_xdr_argument = (xdrproc_t) xdr_export_rename_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_rename_1_svc;
		break;

	case EXPORTPROC_CHMOD:
		_xdr_argument = (xdrproc_t) xdr_export_chmod_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_chmod_1_svc;
		break;

	case EXPORTPROC_TRUNC:
		_xdr_argument = (xdrproc_t) xdr_export_trunc_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_trunc_1_svc;
		break;

	case EXPORTPROC_LIST:
		_xdr_argument = (xdrproc_t) xdr_export_path_args_t;
		_xdr_result = (xdrproc_t) xdr_export_list_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_list_1_svc;
		break;

	case EXPORTPROC_ATTR:
		_xdr_argument = (xdrproc_t) xdr_export_path_args_t;
		_xdr_result = (xdrproc_t) xdr_export_attr_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_attr_1_svc;
		break;

	case EXPORTPROC_READ:
		_xdr_argument = (xdrproc_t) xdr_export_io_args_t;
		_xdr_result = (xdrproc_t) xdr_export_io_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_read_1_svc;
		break;

	case EXPORTPROC_READ_BLOCK:
		_xdr_argument = (xdrproc_t) xdr_export_read_block_args_t;
		_xdr_result = (xdrproc_t) xdr_export_read_block_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_read_block_1_svc;
		break;

	case EXPORTPROC_WRITE:
		_xdr_argument = (xdrproc_t) xdr_export_io_args_t;
		_xdr_result = (xdrproc_t) xdr_export_io_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_write_1_svc;
		break;

	case EXPORTPROC_WRITE_BLOCK:
		_xdr_argument = (xdrproc_t) xdr_export_write_block_args_t;
		_xdr_result = (xdrproc_t) xdr_export_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) exportproc_write_block_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
