/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "export_proto.h"
#include "rozo.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
exportproc_null_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

export_lookup_response_t *
exportproc_lookup_1(export_path_t *argp, CLIENT *clnt)
{
	static export_lookup_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_LOOKUP,
		(xdrproc_t) xdr_export_path_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_lookup_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_statfs_response_t *
exportproc_statfs_1(char *argp, CLIENT *clnt)
{
	static export_statfs_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_STATFS,
		(xdrproc_t) xdr_export_uuid_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_statfs_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_stat_response_t *
exportproc_stat_1(export_path_args_t *argp, CLIENT *clnt)
{
	static export_stat_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_STAT,
		(xdrproc_t) xdr_export_path_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_stat_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_readlink_response_t *
exportproc_readlink_1(export_path_args_t *argp, CLIENT *clnt)
{
	static export_readlink_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_READLINK,
		(xdrproc_t) xdr_export_path_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_readlink_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_mknod_1(export_mknod_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_MKNOD,
		(xdrproc_t) xdr_export_mknod_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_mkdir_1(export_mkdir_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_MKDIR,
		(xdrproc_t) xdr_export_mkdir_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_unlink_1(export_path_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_UNLINK,
		(xdrproc_t) xdr_export_path_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_rmdir_1(export_path_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_RMDIR,
		(xdrproc_t) xdr_export_path_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_symlink_1(export_symlink_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_SYMLINK,
		(xdrproc_t) xdr_export_symlink_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_rename_1(export_rename_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_RENAME,
		(xdrproc_t) xdr_export_rename_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_chmod_1(export_chmod_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_CHMOD,
		(xdrproc_t) xdr_export_chmod_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_trunc_1(export_trunc_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_TRUNC,
		(xdrproc_t) xdr_export_trunc_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_list_response_t *
exportproc_list_1(export_path_args_t *argp, CLIENT *clnt)
{
	static export_list_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_LIST,
		(xdrproc_t) xdr_export_path_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_list_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_attr_response_t *
exportproc_attr_1(export_path_args_t *argp, CLIENT *clnt)
{
	static export_attr_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_ATTR,
		(xdrproc_t) xdr_export_path_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_attr_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_io_response_t *
exportproc_read_1(export_io_args_t *argp, CLIENT *clnt)
{
	static export_io_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_READ,
		(xdrproc_t) xdr_export_io_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_io_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_read_block_response_t *
exportproc_read_block_1(export_read_block_args_t *argp, CLIENT *clnt)
{
	static export_read_block_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_READ_BLOCK,
		(xdrproc_t) xdr_export_read_block_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_read_block_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_io_response_t *
exportproc_write_1(export_io_args_t *argp, CLIENT *clnt)
{
	static export_io_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_WRITE,
		(xdrproc_t) xdr_export_io_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_io_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

export_status_response_t *
exportproc_write_block_1(export_write_block_args_t *argp, CLIENT *clnt)
{
	static export_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, EXPORTPROC_WRITE_BLOCK,
		(xdrproc_t) xdr_export_write_block_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_export_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
