/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "export_proto.h"
#include "rozo.h"

bool_t
xdr_export_status_t (XDR *xdrs, export_status_t *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_uuid_t (XDR *xdrs, export_uuid_t objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, ROZO_UUID_SIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_status_response_t (XDR *xdrs, export_status_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_status_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_hostname_t (XDR *xdrs, export_hostname_t objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, ROZO_HOSTNAME_MAX,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_lookup_response_t (XDR *xdrs, export_lookup_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_export_uuid_t (xdrs, objp->export_lookup_response_t_u.uuid))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_lookup_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_statfs_t (XDR *xdrs, export_statfs_t *objp)
{
	register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->bsize))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->blocks))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->bfree))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->files))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->ffree))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->namemax))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_statfs_response_t (XDR *xdrs, export_statfs_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_export_statfs_t (xdrs, &objp->export_statfs_response_t_u.stat))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_statfs_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_filename_t (XDR *xdrs, export_filename_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ROZO_FILENAME_MAX))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_path_t (XDR *xdrs, export_path_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ROZO_PATH_MAX))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_path_args_t (XDR *xdrs, export_path_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_stat_t (XDR *xdrs, export_stat_t *objp)
{
	register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->mode))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->nlink))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->ctime))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->atime))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->mtime))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_stat_response_t (XDR *xdrs, export_stat_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_export_stat_t (xdrs, &objp->export_stat_response_t_u.stat))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_stat_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_readlink_response_t (XDR *xdrs, export_readlink_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_export_path_t (xdrs, &objp->export_readlink_response_t_u.path))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_readlink_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_chmod_args_t (XDR *xdrs, export_chmod_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_mknod_args_t (XDR *xdrs, export_mknod_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_mkdir_args_t (XDR *xdrs, export_mkdir_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_symlink_args_t (XDR *xdrs, export_symlink_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->target))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->link))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_children_t (XDR *xdrs, export_children_t *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct export_child_t), (xdrproc_t) xdr_export_child_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_child_t (XDR *xdrs, export_child_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_filename_t (xdrs, &objp->file))
		 return FALSE;
	 if (!xdr_export_children_t (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_list_response_t (XDR *xdrs, export_list_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_export_children_t (xdrs, &objp->export_list_response_t_u.children))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_list_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_rename_args_t (XDR *xdrs, export_rename_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->from))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->to))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_attr_t (XDR *xdrs, export_attr_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->uuids, ROZO_SAFE,
		sizeof (export_uuid_t), (xdrproc_t) xdr_export_uuid_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->hosts, ROZO_SAFE,
		sizeof (export_hostname_t), (xdrproc_t) xdr_export_hostname_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_attr_response_t (XDR *xdrs, export_attr_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_export_attr_t (xdrs, &objp->export_attr_response_t_u.attr))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_attr_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_io_args_t (XDR *xdrs, export_io_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->length))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_write_block_args_t (XDR *xdrs, export_write_block_args_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->mb))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nmbs))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->distribution, ROZO_SAFE,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_read_block_args_t (XDR *xdrs, export_read_block_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->mb))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nmbs))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_export_read_block_response_t (XDR *xdrs, export_read_block_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_array (xdrs, (char **)&objp->export_read_block_response_t_u.distribution.distribution_val, (u_int *) &objp->export_read_block_response_t_u.distribution.distribution_len, ~0,
			sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_read_block_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_io_response_t (XDR *xdrs, export_io_response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case EXPORT_SUCCESS:
		 if (!xdr_uint32_t (xdrs, &objp->export_io_response_t_u.length))
			 return FALSE;
		break;
	case EXPORT_FAILURE:
		 if (!xdr_int (xdrs, &objp->export_io_response_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_export_trunc_args_t (XDR *xdrs, export_trunc_args_t *objp)
{
	register int32_t *buf;

	 if (!xdr_export_uuid_t (xdrs, objp->uuid))
		 return FALSE;
	 if (!xdr_export_path_t (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}
