/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXPORT_PROTO_H_RPCGEN
#define _EXPORT_PROTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include "rozo.h"

enum export_status_t {
	EXPORT_SUCCESS = 0,
	EXPORT_FAILURE = 1,
};
typedef enum export_status_t export_status_t;

typedef char export_uuid_t[ROZO_UUID_SIZE];

struct export_status_response_t {
	export_status_t status;
	union {
		int error;
	} export_status_response_t_u;
};
typedef struct export_status_response_t export_status_response_t;

typedef char export_hostname_t[ROZO_HOSTNAME_MAX];

struct export_lookup_response_t {
	export_status_t status;
	union {
		export_uuid_t uuid;
		int error;
	} export_lookup_response_t_u;
};
typedef struct export_lookup_response_t export_lookup_response_t;

struct export_statfs_t {
	uint16_t bsize;
	uint64_t blocks;
	uint64_t bfree;
	uint64_t files;
	uint64_t ffree;
	uint16_t namemax;
};
typedef struct export_statfs_t export_statfs_t;

struct export_statfs_response_t {
	export_status_t status;
	union {
		export_statfs_t stat;
		int error;
	} export_statfs_response_t_u;
};
typedef struct export_statfs_response_t export_statfs_response_t;

typedef char *export_filename_t;

typedef char *export_path_t;

struct export_path_args_t {
	export_uuid_t uuid;
	export_path_t path;
};
typedef struct export_path_args_t export_path_args_t;

struct export_stat_t {
	uint32_t mode;
	uint16_t nlink;
	uint64_t ctime;
	uint64_t atime;
	uint64_t mtime;
	uint64_t size;
};
typedef struct export_stat_t export_stat_t;

struct export_stat_response_t {
	export_status_t status;
	union {
		export_stat_t stat;
		int error;
	} export_stat_response_t_u;
};
typedef struct export_stat_response_t export_stat_response_t;

struct export_readlink_response_t {
	export_status_t status;
	union {
		export_path_t path;
		int error;
	} export_readlink_response_t_u;
};
typedef struct export_readlink_response_t export_readlink_response_t;

struct export_chmod_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint32_t mode;
};
typedef struct export_chmod_args_t export_chmod_args_t;

struct export_mknod_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint32_t mode;
};
typedef struct export_mknod_args_t export_mknod_args_t;

struct export_mkdir_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint32_t mode;
};
typedef struct export_mkdir_args_t export_mkdir_args_t;

struct export_symlink_args_t {
	export_uuid_t uuid;
	export_path_t target;
	export_path_t link;
};
typedef struct export_symlink_args_t export_symlink_args_t;

typedef struct export_child_t *export_children_t;

struct export_child_t {
	export_filename_t file;
	export_children_t next;
};
typedef struct export_child_t export_child_t;

struct export_list_response_t {
	export_status_t status;
	union {
		export_children_t children;
		int error;
	} export_list_response_t_u;
};
typedef struct export_list_response_t export_list_response_t;

struct export_rename_args_t {
	export_uuid_t uuid;
	export_path_t from;
	export_path_t to;
};
typedef struct export_rename_args_t export_rename_args_t;

struct export_attr_t {
	export_uuid_t uuid;
	export_uuid_t uuids[ROZO_SAFE];
	export_hostname_t hosts[ROZO_SAFE];
};
typedef struct export_attr_t export_attr_t;

struct export_attr_response_t {
	export_status_t status;
	union {
		export_attr_t attr;
		int error;
	} export_attr_response_t_u;
};
typedef struct export_attr_response_t export_attr_response_t;

struct export_io_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint64_t offset;
	uint32_t length;
};
typedef struct export_io_args_t export_io_args_t;

struct export_write_block_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint64_t mb;
	uint32_t nmbs;
	uint8_t distribution[ROZO_SAFE];
};
typedef struct export_write_block_args_t export_write_block_args_t;

struct export_read_block_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint64_t mb;
	uint32_t nmbs;
};
typedef struct export_read_block_args_t export_read_block_args_t;

struct export_read_block_response_t {
	export_status_t status;
	union {
		struct {
			u_int distribution_len;
			uint8_t *distribution_val;
		} distribution;
		int error;
	} export_read_block_response_t_u;
};
typedef struct export_read_block_response_t export_read_block_response_t;

struct export_io_response_t {
	export_status_t status;
	union {
		uint32_t length;
		int error;
	} export_io_response_t_u;
};
typedef struct export_io_response_t export_io_response_t;

struct export_trunc_args_t {
	export_uuid_t uuid;
	export_path_t path;
	uint64_t offset;
};
typedef struct export_trunc_args_t export_trunc_args_t;

#define EXPORT_PROGRAM 0x20000003
#define EXPORT_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXPORTPROC_NULL 0
extern  void * exportproc_null_1(void *, CLIENT *);
extern  void * exportproc_null_1_svc(void *, struct svc_req *);
#define EXPORTPROC_LOOKUP 1
extern  export_lookup_response_t * exportproc_lookup_1(export_path_t *, CLIENT *);
extern  export_lookup_response_t * exportproc_lookup_1_svc(export_path_t *, struct svc_req *);
#define EXPORTPROC_STATFS 2
extern  export_statfs_response_t * exportproc_statfs_1(char *, CLIENT *);
extern  export_statfs_response_t * exportproc_statfs_1_svc(char *, struct svc_req *);
#define EXPORTPROC_STAT 3
extern  export_stat_response_t * exportproc_stat_1(export_path_args_t *, CLIENT *);
extern  export_stat_response_t * exportproc_stat_1_svc(export_path_args_t *, struct svc_req *);
#define EXPORTPROC_READLINK 4
extern  export_readlink_response_t * exportproc_readlink_1(export_path_args_t *, CLIENT *);
extern  export_readlink_response_t * exportproc_readlink_1_svc(export_path_args_t *, struct svc_req *);
#define EXPORTPROC_MKNOD 5
extern  export_status_response_t * exportproc_mknod_1(export_mknod_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_mknod_1_svc(export_mknod_args_t *, struct svc_req *);
#define EXPORTPROC_MKDIR 6
extern  export_status_response_t * exportproc_mkdir_1(export_mkdir_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_mkdir_1_svc(export_mkdir_args_t *, struct svc_req *);
#define EXPORTPROC_UNLINK 7
extern  export_status_response_t * exportproc_unlink_1(export_path_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_unlink_1_svc(export_path_args_t *, struct svc_req *);
#define EXPORTPROC_RMDIR 8
extern  export_status_response_t * exportproc_rmdir_1(export_path_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_rmdir_1_svc(export_path_args_t *, struct svc_req *);
#define EXPORTPROC_SYMLINK 9
extern  export_status_response_t * exportproc_symlink_1(export_symlink_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_symlink_1_svc(export_symlink_args_t *, struct svc_req *);
#define EXPORTPROC_RENAME 10
extern  export_status_response_t * exportproc_rename_1(export_rename_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_rename_1_svc(export_rename_args_t *, struct svc_req *);
#define EXPORTPROC_CHMOD 11
extern  export_status_response_t * exportproc_chmod_1(export_chmod_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_chmod_1_svc(export_chmod_args_t *, struct svc_req *);
#define EXPORTPROC_TRUNC 12
extern  export_status_response_t * exportproc_trunc_1(export_trunc_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_trunc_1_svc(export_trunc_args_t *, struct svc_req *);
#define EXPORTPROC_LIST 13
extern  export_list_response_t * exportproc_list_1(export_path_args_t *, CLIENT *);
extern  export_list_response_t * exportproc_list_1_svc(export_path_args_t *, struct svc_req *);
#define EXPORTPROC_ATTR 14
extern  export_attr_response_t * exportproc_attr_1(export_path_args_t *, CLIENT *);
extern  export_attr_response_t * exportproc_attr_1_svc(export_path_args_t *, struct svc_req *);
#define EXPORTPROC_READ 15
extern  export_io_response_t * exportproc_read_1(export_io_args_t *, CLIENT *);
extern  export_io_response_t * exportproc_read_1_svc(export_io_args_t *, struct svc_req *);
#define EXPORTPROC_READ_BLOCK 16
extern  export_read_block_response_t * exportproc_read_block_1(export_read_block_args_t *, CLIENT *);
extern  export_read_block_response_t * exportproc_read_block_1_svc(export_read_block_args_t *, struct svc_req *);
#define EXPORTPROC_WRITE 17
extern  export_io_response_t * exportproc_write_1(export_io_args_t *, CLIENT *);
extern  export_io_response_t * exportproc_write_1_svc(export_io_args_t *, struct svc_req *);
#define EXPORTPROC_WRITE_BLOCK 18
extern  export_status_response_t * exportproc_write_block_1(export_write_block_args_t *, CLIENT *);
extern  export_status_response_t * exportproc_write_block_1_svc(export_write_block_args_t *, struct svc_req *);
extern int export_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXPORTPROC_NULL 0
extern  void * exportproc_null_1();
extern  void * exportproc_null_1_svc();
#define EXPORTPROC_LOOKUP 1
extern  export_lookup_response_t * exportproc_lookup_1();
extern  export_lookup_response_t * exportproc_lookup_1_svc();
#define EXPORTPROC_STATFS 2
extern  export_statfs_response_t * exportproc_statfs_1();
extern  export_statfs_response_t * exportproc_statfs_1_svc();
#define EXPORTPROC_STAT 3
extern  export_stat_response_t * exportproc_stat_1();
extern  export_stat_response_t * exportproc_stat_1_svc();
#define EXPORTPROC_READLINK 4
extern  export_readlink_response_t * exportproc_readlink_1();
extern  export_readlink_response_t * exportproc_readlink_1_svc();
#define EXPORTPROC_MKNOD 5
extern  export_status_response_t * exportproc_mknod_1();
extern  export_status_response_t * exportproc_mknod_1_svc();
#define EXPORTPROC_MKDIR 6
extern  export_status_response_t * exportproc_mkdir_1();
extern  export_status_response_t * exportproc_mkdir_1_svc();
#define EXPORTPROC_UNLINK 7
extern  export_status_response_t * exportproc_unlink_1();
extern  export_status_response_t * exportproc_unlink_1_svc();
#define EXPORTPROC_RMDIR 8
extern  export_status_response_t * exportproc_rmdir_1();
extern  export_status_response_t * exportproc_rmdir_1_svc();
#define EXPORTPROC_SYMLINK 9
extern  export_status_response_t * exportproc_symlink_1();
extern  export_status_response_t * exportproc_symlink_1_svc();
#define EXPORTPROC_RENAME 10
extern  export_status_response_t * exportproc_rename_1();
extern  export_status_response_t * exportproc_rename_1_svc();
#define EXPORTPROC_CHMOD 11
extern  export_status_response_t * exportproc_chmod_1();
extern  export_status_response_t * exportproc_chmod_1_svc();
#define EXPORTPROC_TRUNC 12
extern  export_status_response_t * exportproc_trunc_1();
extern  export_status_response_t * exportproc_trunc_1_svc();
#define EXPORTPROC_LIST 13
extern  export_list_response_t * exportproc_list_1();
extern  export_list_response_t * exportproc_list_1_svc();
#define EXPORTPROC_ATTR 14
extern  export_attr_response_t * exportproc_attr_1();
extern  export_attr_response_t * exportproc_attr_1_svc();
#define EXPORTPROC_READ 15
extern  export_io_response_t * exportproc_read_1();
extern  export_io_response_t * exportproc_read_1_svc();
#define EXPORTPROC_READ_BLOCK 16
extern  export_read_block_response_t * exportproc_read_block_1();
extern  export_read_block_response_t * exportproc_read_block_1_svc();
#define EXPORTPROC_WRITE 17
extern  export_io_response_t * exportproc_write_1();
extern  export_io_response_t * exportproc_write_1_svc();
#define EXPORTPROC_WRITE_BLOCK 18
extern  export_status_response_t * exportproc_write_block_1();
extern  export_status_response_t * exportproc_write_block_1_svc();
extern int export_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_export_status_t (XDR *, export_status_t*);
extern  bool_t xdr_export_uuid_t (XDR *, export_uuid_t);
extern  bool_t xdr_export_status_response_t (XDR *, export_status_response_t*);
extern  bool_t xdr_export_hostname_t (XDR *, export_hostname_t);
extern  bool_t xdr_export_lookup_response_t (XDR *, export_lookup_response_t*);
extern  bool_t xdr_export_statfs_t (XDR *, export_statfs_t*);
extern  bool_t xdr_export_statfs_response_t (XDR *, export_statfs_response_t*);
extern  bool_t xdr_export_filename_t (XDR *, export_filename_t*);
extern  bool_t xdr_export_path_t (XDR *, export_path_t*);
extern  bool_t xdr_export_path_args_t (XDR *, export_path_args_t*);
extern  bool_t xdr_export_stat_t (XDR *, export_stat_t*);
extern  bool_t xdr_export_stat_response_t (XDR *, export_stat_response_t*);
extern  bool_t xdr_export_readlink_response_t (XDR *, export_readlink_response_t*);
extern  bool_t xdr_export_chmod_args_t (XDR *, export_chmod_args_t*);
extern  bool_t xdr_export_mknod_args_t (XDR *, export_mknod_args_t*);
extern  bool_t xdr_export_mkdir_args_t (XDR *, export_mkdir_args_t*);
extern  bool_t xdr_export_symlink_args_t (XDR *, export_symlink_args_t*);
extern  bool_t xdr_export_children_t (XDR *, export_children_t*);
extern  bool_t xdr_export_child_t (XDR *, export_child_t*);
extern  bool_t xdr_export_list_response_t (XDR *, export_list_response_t*);
extern  bool_t xdr_export_rename_args_t (XDR *, export_rename_args_t*);
extern  bool_t xdr_export_attr_t (XDR *, export_attr_t*);
extern  bool_t xdr_export_attr_response_t (XDR *, export_attr_response_t*);
extern  bool_t xdr_export_io_args_t (XDR *, export_io_args_t*);
extern  bool_t xdr_export_write_block_args_t (XDR *, export_write_block_args_t*);
extern  bool_t xdr_export_read_block_args_t (XDR *, export_read_block_args_t*);
extern  bool_t xdr_export_read_block_response_t (XDR *, export_read_block_response_t*);
extern  bool_t xdr_export_io_response_t (XDR *, export_io_response_t*);
extern  bool_t xdr_export_trunc_args_t (XDR *, export_trunc_args_t*);

#else /* K&R C */
extern bool_t xdr_export_status_t ();
extern bool_t xdr_export_uuid_t ();
extern bool_t xdr_export_status_response_t ();
extern bool_t xdr_export_hostname_t ();
extern bool_t xdr_export_lookup_response_t ();
extern bool_t xdr_export_statfs_t ();
extern bool_t xdr_export_statfs_response_t ();
extern bool_t xdr_export_filename_t ();
extern bool_t xdr_export_path_t ();
extern bool_t xdr_export_path_args_t ();
extern bool_t xdr_export_stat_t ();
extern bool_t xdr_export_stat_response_t ();
extern bool_t xdr_export_readlink_response_t ();
extern bool_t xdr_export_chmod_args_t ();
extern bool_t xdr_export_mknod_args_t ();
extern bool_t xdr_export_mkdir_args_t ();
extern bool_t xdr_export_symlink_args_t ();
extern bool_t xdr_export_children_t ();
extern bool_t xdr_export_child_t ();
extern bool_t xdr_export_list_response_t ();
extern bool_t xdr_export_rename_args_t ();
extern bool_t xdr_export_attr_t ();
extern bool_t xdr_export_attr_response_t ();
extern bool_t xdr_export_io_args_t ();
extern bool_t xdr_export_write_block_args_t ();
extern bool_t xdr_export_read_block_args_t ();
extern bool_t xdr_export_read_block_response_t ();
extern bool_t xdr_export_io_response_t ();
extern bool_t xdr_export_trunc_args_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXPORT_PROTO_H_RPCGEN */
