/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage_proto.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include "rozo.h"

void
storage_program_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		storage_remove_args_t storageproc_remove_1_arg;
		storage_write_args_t storageproc_write_1_arg;
		storage_read_args_t storageproc_read_1_arg;
		storage_truncate_args_t storageproc_truncate_1_arg;
		storage_uuid_t storageproc_stat_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case STORAGEPROC_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) storageproc_null_1_svc;
		break;

	case STORAGEPROC_REMOVE:
		_xdr_argument = (xdrproc_t) xdr_storage_remove_args_t;
		_xdr_result = (xdrproc_t) xdr_storage_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) storageproc_remove_1_svc;
		break;

	case STORAGEPROC_WRITE:
		_xdr_argument = (xdrproc_t) xdr_storage_write_args_t;
		_xdr_result = (xdrproc_t) xdr_storage_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) storageproc_write_1_svc;
		break;

	case STORAGEPROC_READ:
		_xdr_argument = (xdrproc_t) xdr_storage_read_args_t;
		_xdr_result = (xdrproc_t) xdr_storage_read_response_t;
		local = (char *(*)(char *, struct svc_req *)) storageproc_read_1_svc;
		break;

	case STORAGEPROC_TRUNCATE:
		_xdr_argument = (xdrproc_t) xdr_storage_truncate_args_t;
		_xdr_result = (xdrproc_t) xdr_storage_status_response_t;
		local = (char *(*)(char *, struct svc_req *)) storageproc_truncate_1_svc;
		break;

	case STORAGEPROC_STAT:
		_xdr_argument = (xdrproc_t) xdr_storage_uuid_t;
		_xdr_result = (xdrproc_t) xdr_storage_stat_response_t;
		local = (char *(*)(char *, struct svc_req *)) storageproc_stat_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
