/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage_proto.h"
#include "rozo.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
storageproc_null_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STORAGEPROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

storage_status_response_t *
storageproc_remove_1(storage_remove_args_t *argp, CLIENT *clnt)
{
	static storage_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STORAGEPROC_REMOVE,
		(xdrproc_t) xdr_storage_remove_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_storage_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

storage_status_response_t *
storageproc_write_1(storage_write_args_t *argp, CLIENT *clnt)
{
	static storage_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STORAGEPROC_WRITE,
		(xdrproc_t) xdr_storage_write_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_storage_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

storage_read_response_t *
storageproc_read_1(storage_read_args_t *argp, CLIENT *clnt)
{
	static storage_read_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STORAGEPROC_READ,
		(xdrproc_t) xdr_storage_read_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_storage_read_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

storage_status_response_t *
storageproc_truncate_1(storage_truncate_args_t *argp, CLIENT *clnt)
{
	static storage_status_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STORAGEPROC_TRUNCATE,
		(xdrproc_t) xdr_storage_truncate_args_t, (caddr_t) argp,
		(xdrproc_t) xdr_storage_status_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

storage_stat_response_t *
storageproc_stat_1(char *argp, CLIENT *clnt)
{
	static storage_stat_response_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STORAGEPROC_STAT,
		(xdrproc_t) xdr_storage_uuid_t, (caddr_t) argp,
		(xdrproc_t) xdr_storage_stat_response_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
